language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=cov
      after_success: coveralls
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: "3.8"
      env: TOXENV=py38
      dist: xenial
      sudo: true

install: pip install -U tox coveralls
script: travis_wait 30 tox
